const teachers = [
  {
    user_id: 7,
    teacher_id: 9,
    first_name: "Ilknura",
    last_name: "Kirgizova",
    image: "profile/I4tzmB9HaY8fniXanEuYuUzOB6wSIqW6MV81V4Zt.png",
    price: 40000,
    description:
      "Har bir o'quvchiga individual yondashuv bo'ladi. O'quvchilarning  ingliz tilida tezroq va osonroq o'rganishiga etibor beriladi.qaysi yo'nalishda passivligi sezilsa ( vocabulary speaking ) osha tarafdan har tomonlama birdek ko'tarilishga e'tibor qaratiladi. Asosan vocabulary va uni ishlata bilish va speaking ga ko'proq bo'ladi. Va bu fikrlash doirasi kengayishiga ham yordam  beriladi.",
    verified: true,
    course_name: "General English",
    student_count: 7,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 21,
    teacher_id: 2,
    first_name: "Maftuna",
    last_name: "Sharapova",
    image: "profile/GaMuG9YITXp6CZl93LpoyRYoZuagWJWHL2dXfg2Z.png",
    price: 50000,
    description:
      "Assalomu alaykum. Men 5 yildan ortiq tajribaga egaman, shundan 3 yilini dars berish bilan birga Gid tarjimon bo'lib ham ishlaganman. CEFR sertifikatiga egaman. Speaking malakangizni oshirmoqchi bo'lsangiz, haqiqiy native speakerlar bilan ishlagan kamina ustozingizga murojaat qilishingiz mumkin. Darslarda har bir o'quvchiga qiziqishlaridan kelib chiqib materiallar tayyorlanadi. Barchangizni kutib qolaman.",
    verified: true,
    course_name: "General English",
    student_count: 8,
    comments_count: 0,
    comments: [],
    star_raytings_count: 5,
    star_raytings: 5,
    loyalty: 100,
  },
  {
    user_id: 117,
    teacher_id: 39,
    first_name: "Gulruh",
    last_name: "Normo'minova",
    image: "profile/OIAUGzKTuYw3pHZUbjpJSyNxKX991muF7b4FiFrb.jpg",
    price: 35000,
    description:
      "Ingliz tilini 0 dan boshlab erkin nutq so'zlash bosqichigacha o'quvchilarga bilimga berish, ularning tilni o'rganishga bo'lgan ishtiyoqini qo'llab quvvatlash. Bakalavr bosqichidan boshlab 4 yil mobaynida o'quvchilarga Ingliz tilidan dars berib kelmoqdaman. Hozirgi kunda magistratura talabasi sifatida, bo'sh vaqtlarimda til o'rganmoqchi bo'lganlarga ushbu platforma orqali onlayn dars bermoqchiman. Myteacher onlayn platformasi orqali oson va qulay usulda uyingizni tark etmasdan tilni mukammal o'rganing",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 150,
    teacher_id: 34,
    first_name: "Mohinur",
    last_name: "Abdulatifova",
    image: "profile/6pQu4dIWI4OfhzF1JETM0BAwc0EarFavPEAd6lp1.png",
    price: 80000,
    description:
      "Ingliz tili bilan 10 yildan beri birga yashayman. Ko'plab yutug'larimga aynan ingliz tili bilan erishganman. Sizga ham maqsadingizga erishishga ko'maklashaman.\r\n-ingliz tilida himoya qilgan maqolam uchun MDH davlatlar o'rtasida yilning eng yosh olimi-2021 nominatsiyasi g'olibi bo'ldim. \r\n-ingliz tilida taqdim qilgan loyiham uchun USAID amerika tashkiloti tomonidan 3 marotaba 1-o'rinni egallab taqdirlandim.\r\n-Aynan ingliz tilini bilganim uchun bir nechta xorijiy davlatlarda ilmiy ishim bilan ishtirok eta oldim\r\n-Hozirgi kunda Ilmiy faoliyat bilan ham shug;ullanib kelaman dunyoning 17dan ortiq davlatlarida maqolalarimni chop etdim. \r\n-Andijon viloyat hokim stipendiyasi sohibasi bo'ldim\r\n-Kuni kecha ingliz tilida bo'lgan xitoydagi bir kursimni tamomladim.\r\n-Respublika Yosh olimlar kengashi a'zosi bo'ldim.\r\n-Erishgan yutuqlarimni sizlar uchun ba'zilarini qisqacha aytib o'tdim. Hammasiga qaysidir ma'noda tilni yahshi ko'rganim va uni o'rganibgina qolmay hayotimga olib kirganim turtki bo'lgan.\r\nSizga Nafaqat ingliz tilida so'zlasha olishni balki sizga grantlar va stipendiyalar yutishni, chet davlatda  o'z loyihalaringiz bilan ishtirok etishni aynan ingliz tilida o'rgataman. Faqatgina ingliz tili emas lider bo'lishni ham o'rganasiz... \r\nAniq maqsadingizga erisha olmayapsizmi, maqsadingizni o'zgartirmang aksincha unga boradigan yo'lni o'zgartiring...",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 151,
    teacher_id: 10,
    first_name: "Asadbek",
    last_name: "Baxtiyorov",
    image: "profile/BGfahEmuiJtVuJLyKhd8YSnJfq2mmltgOcob2mfT.png",
    price: 60000,
    description:
      "Bugungi kunda Ingliz tilini o`qish uchun juda ko`p adabiyotlar va metodlar bo`lishiga qaramay sizlarga ingliz tilini o`rgatishda tuzilgan maxsus dastur orqali imkon qadar tez va samarali o`rgatish uchun shu yerdaman. 2 yillik tajribamda juda ko`p o`quvchilarni 0 darajadan intermediate darajaga olib chiqqanman.",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 178,
    teacher_id: 21,
    first_name: "Kamola",
    last_name: "Xamidova",
    image: "profile/RvIbTWFddJ92cbAAoCs1PqSU1dCOydMhYfqIaw7I.png",
    price: 30000,
    description:
      "Hozirda O'zbekistonda ingliz tilini o'rganish yanada yuqori bosqichga chiqdi, raqobat talaygina ammo sifatli va raqobatbardosh bilim olish barchani o'ylantirayotgan masaladir. General English da men o'quvchilarimga nafaqat ingliz tili grammatikasini  o'rgataman, balki uni muloqot va yozishish malakasida qanday qo'llash uslublarini o'rgataman. Zero, general English bu-ingliz tilining barcha jabhalarini qamrab oladi (reading 📖 writing 📝 speaking 🗣️ listening 🎧). Bu mashaqqatli ammo qiziqarli yo'lda men sizlarga yordam beraman. Hammangizga omad yor bolsin!!!",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 189,
    teacher_id: 27,
    first_name: "Maryamxon",
    last_name: "Alisherova",
    image: "profile/hwWWrKkZYpoAznEgOde1luAl43jRdoqZQNYj3srk.png",
    price: 50000,
    description:
      "Biz bilan ingliz tilini istalgan vaqtda va òzingizga qulay joyda òrganing!\r\nDarslar maxsus dastur va vaqt bilan ishlab chiqilgan:\r\n1. General English- 5 oy 6 ta kitob\r\n2. IELTS preparation-6 oy 8 ta kitob\r\n3. Essay evaluation with feedback-2 oy \r\n4. Special speaking trainings-2 oy\r\n5. Kids English- bolajonlar uchun maxsus dastur asosida qiziqarli ingliz tili\r\nDarslar zoom platformasi orqali òtiladi!\r\nHar bir òquvchiga individual shaklda!\r\nShoshiling joylar soni chegaralangan!",
    verified: false,
    course_name: "IELTS",
    student_count: 7,
    comments_count: 3,
    comments: [
      {
        last_name: "Каратаев",
        first_name: "Отабек",
        created_at: "2022-02-18 08:50:35",
        image: null,
        content: "Уз устида ишлайди. Яхши тушунтиради. Талабчан.",
      },
      {
        last_name: "Каратаев",
        first_name: "Отабек",
        created_at: "2022-02-18 08:50:46",
        image: null,
        content: "Уз устида ишлайди. Яхши тушунтиради. Талабчан.",
      },
      {
        last_name: "Каратаев",
        first_name: "Отабек",
        created_at: "2022-02-18 08:50:52",
        image: null,
        content: "Уз устида ишлайди. Яхши тушунтиради. Талабчан.",
      },
    ],
    star_raytings_count: 3,
    star_raytings: 5,
    loyalty: 100,
  },
  {
    user_id: 190,
    teacher_id: 25,
    first_name: "Asal",
    last_name: "Maksudova",
    image: "profile/Ig49u3hNeqcGvekv8f2y0js5JFHg5lWCxN1AOLIK.png",
    price: 40000,
    description:
      "3 ой ичида рус тилида тулик сузлашиш ва грамматикани хам тушуниш ва куллаб билишни кафолат бераман. Дарс жарайонида : сузлашув,видео ва слайд бн ишлаш, матнларни таржима килиш ва суз йодлаш булади.\r\nНульдан бошлаб урганмокчи булган укувчиларга хам имконият бор !. Имкониятни кулдан бой берманг ва тезрок рус тилида сузлашишни бошланг",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 193,
    teacher_id: 29,
    first_name: "Mehrangiz",
    last_name: "Hojiyeva",
    image: "profile/UVndqSLCcosX2raiBJy6nLJB28900smTyxTLgjMy.png",
    price: 60000,
    description:
      "Darslarni qiziqarli interactive usullarda olib boraman. Bitta dars davomida mavzulashtirilgan listening, reading, writing, speaking va vocabulary ustida ham ishlaymiz. Asosan speaking va vocabularyga e'tibor qarataman.\r\n6 oyda 7, 8 oyda 8 olasiz deb va'da bermayman. Zotan hammasi o'zingizni harakatingizga bog'liq.",
    verified: true,
    course_name: "IELTS",
    student_count: 7,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 195,
    teacher_id: 30,
    first_name: "Muazzam",
    last_name: "Mirzayeva",
    image: "profile/lH2jZRYw1yWgScqw18M0y9ea9jWG4HyerRpcpNGa.png",
    price: 50000,
    description:
      "Darslar kop qisimlardan iborat boladi. Óquvchining maqsadlariga qarab, \r\nRazgovorniy, grammatika, universitet uchun tayyorgarlik korish yoki umuman rus tilini toliq órganish. Bu uchun hammasi toliq organiladi. Vazifalar ham shunga yarasha kop boladi.\r\nP.S \r\nVazifa qilinmagan bolsa,  u oquvchiga dars ótilmaydi))\r\nBu óquvchini vaqtida darsga kirishi va yaxwi ózlashtirishini taminlaydi)",
    verified: false,
    course_name: "Rus tili",
    student_count: 8,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 211,
    teacher_id: 45,
    first_name: "Gulsanam",
    last_name: "Oʻngalboyeva",
    image: "profile/wy6xdNgz8SFDBeE6F8t0mBQeInCx802aFn3VTiUS.jpg",
    price: 40000,
    description:
      "General English\r\n√ Speaking 🗣️\r\n√ Reading 📚\r\n√ Listening 🎧\r\n√ Writing 🖊️\r\n\r\nIntensiv darslar & sifatli taʼlim & hamyonbop narxlar & qisqa fursatlar \r\nShunday ilm oʻrganingki, ilmingiz tufayli ziyoyi chashmasi olamlarga tatigulik boʻlsin...",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 215,
    teacher_id: 37,
    first_name: "Barnoxon",
    last_name: "Yakubova",
    image: "profile/YSfIg8O2Sbvwd9fI9uEvyKmm05KQfA38A5VW7VU9.jpg",
    price: 30000,
    description:
      "Sodda va tushunarli. 1 oy davomida harf o'rganib, ikkinchi oyda arab tilida yoza boshlaysiz. Uchinchi oydan esa o'qishni o'rganasiz! Eng asosiysi 3 oy davomida 200 dan ortiq so'z yodlaysiz! Boshlang'ich ta'limga ega bo'lasiz!",
    verified: false,
    course_name: "Arab tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 222,
    teacher_id: 40,
    first_name: "Fakhriddin",
    last_name: "Jabbarov",
    image: "profile/eOq91DyWPD2056DVERL5QxqyYoaue1XLivOnmPK5.jpg",
    price: 100000,
    description:
      "Bir necha yillar tajribaga ega, o'z dars o'tish uslubiga ega, chet elda malaka oshirgan o'qituvchi. 3 yoshdan yuqori o'rganuvchilarni darslarimizga taklif qilamiz. Darslar siz istagan tilda o'tiladi.\r\nVetnam davlatida bir necha yillar tajriba ortirgan.",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 246,
    teacher_id: 57,
    first_name: "Малика",
    last_name: "Абдулхакова",
    image: "profile/s4ZwTMPnLYccmhlU2f9CdcTGdLBVgN8TLjSffm6K.jpg",
    price: 10000,
    description:
      "Hurmatli o'quvchilar agar sizga sodda va tushunarli tilda ma'lumot yetkaza oladigan o'qituvchi kerak bo'lsa topdim deb hisoblayvering. Ish tajribasi albatta mavjud. Kreativ yondashuv albatta kafolatlanadi! Oliy ma'lumotli va 2 yillik tajribaga ega bolgan matematika o'qituvchisi.",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 320,
    teacher_id: 58,
    first_name: "Gulnoza",
    last_name: "Ubaydullayeva",
    image: "profile/nID7vxppuS82GwcBMIstleZQ0e0fK2rqN6AyXiAy.jpg",
    price: 70000,
    description:
      "Darslar oson, sodda va yengil o'tilishi tarafdoriman. Umuman Rus tilini bilmaydigan o'quvchi tilga ko'nikma hosil qilib, bazaviy bilimlarni egallashi uchun o'z ona tilini qo'llayman - bu qulay va bu to'g'ri deb hisoblayman.\r\nSal tili kelishgan studentlarim bilan Esa ko'proq tajriba ustida ishlashni xohlayman. Til baryerini olive tashlash yarım g'alaba!",
    verified: false,
    course_name: "Rus tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 395,
    teacher_id: 69,
    first_name: "Dilshodbek",
    last_name: "Toshpo'latov",
    image: "profile/rROTjLDabzAWLnKkuqVSQROo4BcUXxvVrZ88wnrz.png",
    price: 60000,
    description:
      "Arab tilini o'rganmoqchi bo'lganlarga noldan boshlab gramatika va so'zlashuvni o'rgatamiz. Darslar juda ham qiziqarli va mazmunli o'tadi. O'quvchidan talablarim xohish va tirishqoqlik va darsga o'z vaqtida kirish. Arab tiliga qo'shimca ravishda xattotlik darslarimiz ham bor",
    verified: false,
    course_name: "Arab tili",
    student_count: 5,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 403,
    teacher_id: 70,
    first_name: "Ro'zimuhammad",
    last_name: "Sidiqov",
    image: "profile/Rozimuhammad.jpg",
    price: 10000,
    description:
      "Men asosan darslarni grammatikalarni video roliklarda, ko'proq ikkinchi shaxs bilan muloqot qilish bo'yicha dars olib boraman hamda topik, ish uchun (jeton E9 viza) testlari o'rgataman...\n\"Mening shiyorim ilm ustida qancha kurashsangham shuncha oz\"...",
    verified: false,
    course_name: "Koreys tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 406,
    teacher_id: 80,
    first_name: "Maftuna",
    last_name: "Turatova",
    image: "profile/DWRWhAK2ZCvTlNJDOCKITi2RxNNC71k8jZ9ciGyE.jpg",
    price: 40000,
    description:
      "Hi...!👋 I'm Maftuna your 5 year's English teacher. I welcome you with IELTS , CEFR, APTIS, TEFL, TESOL COURSES and Funny English with little kids. It will be awesome 👌 and wonderful journey 😀!!! \r\nI'm waiting you, my dears!!!",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 411,
    teacher_id: 201,
    first_name: "Nodira",
    last_name: "Xazratqulova",
    image: "profile/y8kEhE76oTWQiLEV2bZNBGtMnFFBXnROC9qwtwTh.png",
    price: 35000,
    description:
      "Har bir o'quvchiga salohiyatidan kelib chiqib yondashaman. Lekin qattiqo'lman. Darslarni amaliy mashqlar bilan qilinishga  va o'zi mustaqil qilishga qo'yib beraman.Chunki mani bilimim o'quvchiga dars jarayonida o'tib qolmaydi. Darsdan tashqari savollariga javob beraman yoki tushunmagan mavzuni boshqatdan tushuntirib berman. Qo'ldan kelgancha",
    verified: false,
    course_name: "Koreys tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 420,
    teacher_id: 73,
    first_name: "Шаходат",
    last_name: "Исломова",
    image: "profile/YU5r36EpIMon9NCn6XMofK4MRFZYTmlWNHHi2ZE5.png",
    price: 25000,
    description:
      "Рус тили хоззирда оммалашган тил хисобланиб, уни урганиш сизга керак болябтими? Урганиш кийинчилик тугдирябтими, унда келинг мен сизга ёрдам бераман. Дарсларни мукаммал тарзда олиб борамиз. Сиз хохлаган,истаган усулда. Рус тилини урганишда, су́з ёдлашлар оркали, машклар, тест ишлашлар, матн укишлар оркали урганишга харакат килинади.",
    verified: false,
    course_name: "Rus tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 422,
    teacher_id: 132,
    first_name: "Zarifa",
    last_name: "Rasulova",
    image: "profile/ethal1Pka09ukvLH6StYm33cSzEUMh0mDRKOumhU.png",
    price: 50000,
    description:
      "Что обо мне? Меня зовут Зарифа, в данный момент обучаюсь в университете на лингвиста, филолога английского языка. Могу с уверенностью сказать, что знаю английский язык на уровень B2 или чуть выше\r\nПомогу вам освоить азы английского, или поднять ваш уровень языка, если вы продолжающий) Провожу уроки на русском или английском языках, в соответствии с вашим уровнем и предложениями. Welcome)",
    verified: false,
    course_name: "IELTS",
    student_count: 4,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 492,
    teacher_id: 83,
    first_name: "Zarina",
    last_name: "Sayfulloeva",
    image: "profile/Pw761pKQjEgwMEVOiMEPJbXhFvX26WiRIawPXvg9.png",
    price: 40000,
    description:
      "Bir narsani aniq tushuntirmagunimcha tuxtamayman. Ammo bir necha marotaba aniq tushuntirishdan keyin ham. Agar tushunmasangiz jahlim chiqadi. Grammatika, pre IELTS. IELTS ham oʻta olaman. Soʻzlashuv va boshqa skillarni ham. Darslarni noldan boshlashim ham mumkin. Har bir oʻquvchini avval darajasini aniqlab keyin dars boshlamiz. Zamonlar predlog, hatto articl va shunga oʻxshash mavzularni mukammal bilaman",
    verified: false,
    course_name: "General English",
    student_count: 14,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 631,
    teacher_id: 86,
    first_name: "Ruzimuhammad",
    last_name: "Sidiqov",
    image: "profile/Rozimuhammad.jpg",
    price: 40000,
    description:
      "Har bir o'quvchiga individual yondashuv bo'ladi. O'quvchilarning qaysi yo'nalishda passivligi sezilsa o'sha tarafdan har tomonlama birdek ko'tarilishga e'tibor qaratiladi. Asosan video roliklar va uni ishlata bilish va suhbatlashish ko'proq bo'ladi. Va bir fikrlash doirasi kengayishiga ham yordam beriladi.",
    verified: false,
    course_name: "Rus tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 955,
    teacher_id: 97,
    first_name: "Алеся",
    last_name: "Саяпина",
    image: "profile/gbrcpoJwuw61tGAJAAMHBxjpiUDT4ZloXp3390M8.jpg",
    price: 40000,
    description:
      "Индивидуальный подбор программы, который осуществляется в зависимости от ваших предпочтений.\nОриентированность на результат и качество освоения русского языка.\nАудирование, говорение, чтение-вот что мы осваиваем на уроках, письмо по вашему желанию. \nРусский язык-очень интересный, красивый. Понимая русскую речь, научившись говорить, вы оцените все его достоинства. \nВместе мы добьёмся отличного результата!",
    verified: true,
    course_name: "Rus tili",
    student_count: 12,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1000,
    teacher_id: 102,
    first_name: "Gulshod",
    last_name: "Sultonova",
    image: "profile/YElSGHGuIoTbYljSIDdN5FwQLbVERSydvhxS3NJ9.png",
    price: 50000,
    description:
      "Men 30 yildan buyon rus tili fani òqituvchisiman.Faoliyatim davomida kòplab metodlar ustida ishlaganman va amaliyotda qòllaganman.Men fanimni òqitish davomida turli xil va interaktiv metodlardan foydalangan holda òrgataman.Òquvchilar bilan alohida shuģullanaman.Har bir òquvchimni òzlashtirish darajasidan kelib chiqib topshiriqlar beraman",
    verified: true,
    course_name: "Rus tili",
    student_count: 7,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1015,
    teacher_id: 101,
    first_name: "Lana",
    last_name: "L",
    image: "profile/Lana.jpg",
    price: 65000,
    description:
      "К каждому студенту применим индивидуальный подход, исходя из его начальных знаний. В процессе изучается грамматический материал, разговорная часть, по желанию или по необходимости-письменность. Главная наша цель  - результат И совершенствование,в чем мы будем способствовать.  Используются \r\n различные учебные пособия и практики.",
    verified: true,
    course_name: "Rus tili",
    student_count: 5,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1263,
    teacher_id: 151,
    first_name: "Mohinur",
    last_name: "Sanoqulova",
    image: "profile/OyDs0SdBJPFABZylrJGGMhyiYm6qXfOSaiaTlluR.png",
    price: 25000,
    description:
      "Avval mavzuni to‘liq tushuntirib, keyin o'sha mavzuni mustahkamlash un turli xil test va savollar olaman.  Har bir o'quvchiga alohida e'tibor qaratib,har biri bilan chuqur shug'ullanaman. Imtihonga tushadigan savollar bilan ko'proq ishlayman. Ona tilini to‘liq o'tganimdek, adabiyot fanidan ham  to‘liq o'ta olaman. Kechki 19:00dan 22:00gacha bo‘shman",
    verified: false,
    course_name: "Ona tili va adabiyot",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1469,
    teacher_id: 157,
    first_name: "Anisa",
    last_name: "Sharipova",
    image: "profile/UJ3OO7vrHT5heO42zga6bIO2BEQMgYWvHnqzmuxd.png",
    price: 60000,
    description:
      "Bilamizki, hammaning dars o'tish uslubi va darsliklari har xil. Barcha o'qituvchilar o'zlari bilgan yo'nalishda dars o'tishadi. Fikrimcha dars o'tish davomida o'quvchi bilan erkin muloqot qilgan va motivatsiyalar bergan holda dars o'tish yaxshi samara berishi o'z isbotini topgan. Shuning uchun men doim darslarimni oliy darajada o'quvchilarim bilan hamkorlikda o'tishga harakat qilaman. Ilm o'rganish uchun inson, hamma narsaga, hattoki sarmoya kiritishga ham tayyor bo'lishi kerak. Zeroki, bu ertaga ming barobar bo'lib qaytadi. Hozir boshlang qadrli bilimga chanqoqlar. Ertaga kech bo'lishi mumkin.",
    verified: false,
    course_name: "IELTS",
    student_count: 1,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1491,
    teacher_id: 164,
    first_name: "Gulhayo",
    last_name: "Maxmudova",
    image: "profile/32gVakIFQwiVfquyOF0BczpyLP50wQeyXs0eKPSi.png",
    price: 50000,
    description:
      "Til o'rgana olish ham katta qobiliyatdir. Men o'z o'quvchilarimni individual tarzda o'qitib, bilinlarini oshirishga yordam beraman. 5 yillik tajribaga ega, inson sifatida ularga, ingliz tili grammatikasi, gapirish, tinglab tushunish, o'qib tushunish, yozish ko'nikmalarini oshirishda ularga hamroh bo'laman. \r\nItalyan tilini o'rganmoqchi bo'lganlar uchun ham maxsus kurs ochiladi",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1493,
    teacher_id: 172,
    first_name: "Laylo",
    last_name: "Abdullayeva",
    image: "profile/oUZFl7KjkpkWCTwz0XToA6jm20Pr0Vr2G6f3yi6D.png",
    price: 40000,
    description:
      "Ingliz tilini 0dan boshlab o'rgataman. Ingliz tilida to'gri o'qish talaffuz qilish bilan 4 skill yani speaking listening reading writingni o'rgataman. Har xil usullar kreativ fikrlashga undovchi texnika va usullar bn ingliz tilini o'rganish imkoni sizda bor",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1509,
    teacher_id: 168,
    first_name: "Dilnoza",
    last_name: "Inoyatova",
    image: "profile/Pt0P6j2j2BvV4TwC0ZbrOiTC9DUQxsCEh373dldD.png",
    price: 50000,
    description:
      "Men Buxoro Davlat Universitetida Lingvistika (Ingliz tili bo'yicha) 2-kurs magistranti bo'laman. Shuningdek dars berish bo'yicha 3 yildan ortiq tajribaga egaman. IELTS va CEFR sertifikatlarim ham bor. MyTeacher (Oldingi Webclass davridan) platformasida qariyib 3 yildan ortiq vaqt davomida online dars berib kelmoqdaman. O'quvchilarim juda yaxshi natijalarga erishmoqdalar.",
    verified: false,
    course_name: "General English",
    student_count: 4,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1514,
    teacher_id: 169,
    first_name: "Moxi-Sitora",
    last_name: "Akramova",
    image: "profile/U2c6rinLlsITDLOpmMQWjGivOHMCbjmmD5fx9IAK.png",
    price: 40000,
    description:
      "Men albatta Amerikani ochmayman,ammo Ingliz tilini órganish qanchalar oson va qiziqarli ekanligini men bilan birga bilib olasiz. Darslarimda órganuvchining talab ba takliflaridan kelib chiqqan holda yondashaman va qulayliklar yaratishga harakat qilaman. English journey ni birga bosib òtamiz.",
    verified: false,
    course_name: "General English",
    student_count: 2,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1516,
    teacher_id: 170,
    first_name: "Durdona",
    last_name: "Botirova",
    image: "profile/FvolCDBJyRU1PSV2i6yHas1OEiZzzjLpHCJhDWL8.png",
    price: 50000,
    description:
      "O'quvchilar bilan ularning bilim salohiyatidan kelib chiqqan holda dars o'taman. Audio darsliklar, yangi elektron darsliklardan foydalanaman. O'quvchilarning tolga bo'lgan qiziqishini oshirishga harakat qilaman.",
    verified: false,
    course_name: "Koreys tili",
    student_count: 3,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1564,
    teacher_id: 176,
    first_name: "Munira",
    last_name: "Rakhmonova",
    image: "profile/CI1WkhmRhp7AvxYeykLMMf1GpMhuslJy3wdPyXgn.png",
    price: 40000,
    description:
      "Dars o'qtish tartibim yangi mavzuni qiziqarli qilib tushintirib beraman va ularga kundalik yangi so'zlar beraman va boshqa turli xil activitylar qilaman. Vazifalarni va uy vazifalarni vaqtida so'rab boraman. Bundan tashqari mavzuga talluqli testlar ham tashkil qilaman ularni haftalik najitalarini o'rganib boraman.",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1620,
    teacher_id: 183,
    first_name: "Madina",
    last_name: "Hayitova",
    image: "profile/UonuLrS1ImmN45BcehoPNcsEzQ73IQEQjjmsO3Qi.png",
    price: 40000,
    description:
      "Hozirgi asrda oʻz tilimizdan tashqari boshqa tillarni bilish koʻp yoʻllarni koʻrsatadi va koʻplab eshiklarga kalit boʻla oladi.Ba'zida shunday vaqtlar boʻladiki chet tillaridagi har xil medialarni koʻrganingizda yoki eshitganingizda ularni tarjima qilishni va tushunishni xoxlaysiz.Shundagina sizda tilga ehtiyojingiz kuchayadi...",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1649,
    teacher_id: 186,
    first_name: "Durdona",
    last_name: "Shukurova",
    image: "profile/8NE7XHFE7ORlx4qTdhSZtWykFhslSRlu1eMKjXHz.png",
    price: 50000,
    description:
      "Ingliz tilining Beginner, intermediate, pre-intermediate hamda upper-intermediate darajadagi o'quvchilari uchun samarali darslar o'tishga harakat qilamiz. Darslar 4 ta skill bo'yicha to'liq olib boriladi.",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1720,
    teacher_id: 191,
    first_name: "Munojat",
    last_name: "Kamolova",
    image: "profile/wyHl5tcGDDidG711xqaCJDWUIHxxPf5DqXMmEdql.png",
    price: 20000,
    description:
      "IELTS imtihoniga tayyorlanish oson protsess emas. 4 ta skill, ya'ni listening, reading, writing, speaking ham o'z navbatida bir qancha turlarga bo'linadi. Masalan reading: True/False/Not given, matching headings...\nListening: multiple choice questions, gap filling va hokazo. Man boshlamoqchi bo'lgan kurs davomida har bir skill va ular qamrab oluvchi boshqa shunday yo'nalishlarning har biri birma-bir alohida darslarda batafsil tushuntiriladi.",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1773,
    teacher_id: 194,
    first_name: "Marjona",
    last_name: "Temirova",
    image: "profile/cJdstWt2OYMTsteE3NQEvNxRVJAE26hh9t7nz2ji.png",
    price: 60000,
    description:
      "O'z yo'nalishim mutaxassisi sifatida shuni ayta olamanki, o'rganuvchini qiziqtira bilish va o'rganuvchi  uchun qiziq bo'lgan sferalar ustida ko'proq ishlash, o'rganish jarayonini va vaqtini unumdor qiladi. O'quvchilarim bilim va qiziqshiga e'tibor bergan holda bosqichma-bosqich yuqoriga ko'tarilamiz. Ha, aytgancha yana bir afzallik, darslarni tonggi soat 5-6 yoki kechki soat 23-24 atrofida ham o'ta olamiz, ayni shu paytlar o'rganuvchi uchun ham o'qituvchi uchun ham kun davomidagi rejalarini bajarishida vaqtning unumdorligini ta'minlaydi. Qani, ketdikmi Ingliz dunyosi bo'ylab sayohatga?",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1801,
    teacher_id: 196,
    first_name: "Zukhra",
    last_name: "Reyimbergenova",
    image: "profile/o7MDCh5OX2JaMpBtF2I19D7FPpk60WVgLSOgcwPt.png",
    price: 60000,
    description:
      "Darslar qiziqarli kitoblar va audio podkastlar yordamida o'tkaziladi. \r\nO'quvchilardan eng birinchi darsga bo'lgan hurmat va javobgarlikni talab qilardim, berilgan topshiriqlar bajarilmasa va mas'ulyatsizlik holatlari uchrasa darslarni davom ettira olamiz deyishim qiyin.",
    verified: false,
    course_name: "General English",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1879,
    teacher_id: 198,
    first_name: "Zarina",
    last_name: "Jamolova",
    image: "profile/xXyB2UPtzD2ZMqb3zoNeD15j7oDOZIeXT8lHZOVJ.png",
    price: 50000,
    description:
      "\"Rus tilini qisqa muddatda ravon so'zlashishga o'rgataman\" degan gaplarni ishlatib o'tirmayman. Chunki shunday bo'lganda o'qituvchi izlab yurmagan bo'lardingiz. \"Razgovorniy\"ga yo'naltirilgan davomli kurslar o'taman. Ming bor eshitgandan bir bor ko'rgan afzal. Keling sinov darslarida o'zingiz ko'rib baho bering. Rus tilini o'rganish istagida o'z ustida ishlab natijaga erishmoqchi bo'lgan va bu yo'lda vaqtini, kuchini va mehnatini sarflashga tayyor bo'lgan o'quvchilarni darslarimda kutib qolaman.",
    verified: false,
    course_name: "Rus tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1907,
    teacher_id: 203,
    first_name: "Shahnoza",
    last_name: "Azizova",
    image: "profile/8BybYRJduH3AWae3VCfnLBvOVZGY5b1yvyBrbp7c.png",
    price: 20000,
    description:
      "Siz ózingiz xohlagan vaqtda va sharoitda til órganishni istaysizmi ??? Mana shunday imkoniyat berilmoqda . Sizni óz darslarimga taklif qilaman . Siz bu kurs orqali ingliz tilini boshlang'ichdan toki IELTS darajagacha yoki General English darslarini individual shaklda ,qóshimchasiga alohida SPEAKING ,LISTENING ( bolajonlar uchun maxsus), READING va WRITING traininglarda ishtirok etishingiz mumkin . SIZNI KURSIMIZGA HURMAT BILAN TAKLIF QILAMAN !!! . Thank you for your attention !!!",
    verified: false,
    course_name: "IELTS",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1913,
    teacher_id: 206,
    first_name: "Nuriddin",
    last_name: "Sharapov",
    image: "profile/xZWaCB4QcXZPCpWMEWADcpwtBEqQdGZ5bvx3Uy05.png",
    price: 50000,
    description:
      "Rus tilini individual tarzda zoom orqali o'rganing. 20 yildan ortiq tajribamdan kelib chiqib, tilni aynan sizning darajangiz, o'zlashtirish tezligingiz, qiziqishlaringiz hamda qobiliyatingizdan kelib chiqib o'rgataman. Dars davomida suhbatlashish malakasiga koproq e'tibor beramiz. Turmushdagi har xil vaziyatlar va holatlard qanday gapirish kerakligini o'rganamiz. Bundan tashqari, grammatik qoidalarni ham men bilan chuqurlashtirilgan holda o'rganishingiz mumkin.",
    verified: false,
    course_name: "Rus tili",
    student_count: 0,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
  {
    user_id: 1989,
    teacher_id: 208,
    first_name: "Samandar",
    last_name: "Mirjaloloff",
    image: "profile/l76QwGYq0R98m5GEEetndKe6C55bTnhvsUBAMCu9.png",
    price: 25000,
    description:
      "Uzoq gapirmayman, meni tanlab adashmaysiz. Bu katta gapirish emas, lekin darslarimga qatnasha boshlab boshqa darsga kirgingiz kelmay qoladi. Bu uslubim va yillar davomida yiqqan tajribalarim samarasi. Sinov darsiga yoziling va guvohi bo'ling.",
    verified: true,
    course_name: "General English",
    student_count: 2,
    comments_count: 0,
    comments: [],
    star_raytings_count: 0,
    star_raytings: 0,
    loyalty: 100,
  },
];

module.exports = teachers;
